import EventList from "@/components/events/event-list";
import EventsSearch from "@/components/events/events-search";
import { getAllEvents } from "@/dummy-data";
import Head from "next/head";
import { Fragment } from "react";
import { useRouter } from "next/router";

function EventsPage() {
  const allEvents = getAllEvents();
  const router = useRouter();
  const findsEventsHandler = (year, month) => {
    router.push(`/events/${year}/${month}`);
  };

  return (
    <>
      <Head>
        <title>Events page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <EventsSearch onSearch={findsEventsHandler} />
        <EventList items={allEvents} />
      </Fragment>
    </>
  );
}

export default EventsPage;
