import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { getFeaturedEvents } from "@/dummy-data";
import EventList from "@/components/events/event-list";

import { getAllEventsFromFirebase } from "@/helpers/api-utils";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage(props) {
  const featuredEvents = props.featuredEvents;
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <div className={inter.className}>
        <EventList items={featuredEvents} />
      </div>
    </>
  );
}

export async function getStaticProps() {
  let featuredEvents = null;
  const allEvents = await getAllEventsFromFirebase();

  if (allEvents) {
    featuredEvents = await getFeaturedEvents(allEvents);
  }
  return {
    props: {
      featuredEvents,
    },
  };
}
